### ISSUE TITLE
Include the user id in the rating table, and returns the user id, score and the comment, in the comments return of the rating API

### ISSUE THREAD

**Issue by vicetr3s** [fraco-oxza/utalEats#15]
Returns the user id and user score in the rating API response, in addition to the user comment. To do this, there has to be an user id in the rating table. This is necessary to make the design made in Figma.

**Comment by fraco-oxza** [comment]
Okey, I'm working.

**Comment by fraco-oxza** [comment]
@vicetr3s, I'm not sure we should include those things, since they're not mentioned in the professor's document. I think returning the score for each comment is fine, but returning the user ID might not be, as it could be related to maintaining the anonymity of the reviewers, for example.

**Comment by vicetr3s** [comment]
@fraco-oxza Yes, you are right about the user id, I have thought about it and is going to be complicated maintaining the anonymity given the endpoints we have right now.  Having the individual score will be enough.
