### ISSUE TITLE
Missing Password Confirmation on Account Creation

### ISSUE THREAD

**Issue by fraco-oxza** [fraco-oxza/utalEats#35]
The frontend currently lacks a password confirmation field during account creation.  This increases the risk of users accidentally entering incorrect passwords.

  Add a password confirmation field to the account creation form on the frontend, ensuring both password fields match before submission.  Include client-side validation to alert the user if the passwords do not match.

**Comment by vicetr3s** [comment]
I am working on it.

**Comment by fraco-oxza** [comment]
@vicetr3s is it ready? If so, close the issue because Benja already did it.

**Comment by vicetr3s** [comment]
@fraco-oxza Yes, is ready.
